Update cd.yml

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -65,6 +65,16 @@ jobs:
       # - name: Build the React app
       #   run: npm run build
 
+      - name: Verify AWS S3 Connection
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_REGION: 'us-east-1'  # Update to your AWS region
+        run: |
+          echo "Checking AWS S3 connection..."
+          aws s3 ls s3://frontend-bat || exit 1
+        continue-on-error: false  # Ensures the job fails if connection fails
+
       - name: Deploy to S3
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
