Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -2,39 +2,54 @@ name: Python application
 
 on:
   pull_request:
-    branches: [ "main" ]
-    paths:
-      - 'backend/**'
+    branches:
+      - main
+
 jobs:
   build:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v4
+      - name: Checkout repository
+        uses: actions/checkout@v4
 
-    - name: Set up Python 3.10
-      uses: actions/setup-python@v3
-      with:
-        python-version: "3.10"
+      - name: Set up Python 3.10
+        uses: actions/setup-python@v3
+        with:
+          python-version: "3.10"
 
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install flake8 pytest
-        pip install pytest-cov
-        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+      - name: Check if backend directory has changes
+        id: check_backend_changes
+        run: |
+          if git diff --quiet HEAD^ HEAD -- backend; then
+            echo "backend_modified=false" >> $GITHUB_ENV
+          else
+            echo "backend_modified=true" >> $GITHUB_ENV
+          fi
 
-    - name: Test with pytest
-      id: run_tests
-      run: |
-        pytest
+      - name: Install dependencies
+        if: env.backend_modified == 'true'
+        run: |
+          python -m pip install --upgrade pip
+          pip install flake8 pytest pytest-cov
+          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
 
-    - name: Evaluate Test Results
-      if: steps.run_tests.outcome == 'failure'
-      run: |
-       echo "Tests failed. Setting job status to failed."
-       exit 1
-    - name: Tests Passed
-      if: steps.run_tests.outcome == 'success'
-      run: echo "Tests passed successfully!"
+      - name: Test with pytest
+        id: run_tests
+        if: env.backend_modified == 'true'
+        run: |
+          pytest
+
+      - name: Evaluate Test Results
+        if: env.backend_modified == 'true' && steps.run_tests.outcome == 'failure'
+        run: |
+          echo "Tests failed. Setting job status to failed."
+          exit 1
+
+      - name: No Changes in Backend Directory
+        if: env.backend_modified == 'false'
+        run: echo "No changes in backend directory, marking job as passed."
+        
+      - name: Tests Passed
+        if: env.backend_modified == 'true' && steps.run_tests.outcome == 'success'
+        run: echo "Tests passed successfully!"
